version: '3.6'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file: ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    expose:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data 
volumes:
  db-data:
