version: '3.6'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - 3200:3200
    env_file: ./frontend/.env
      
